### ISSUE TITLE
Я установил плагин и все зависимости, но когда я набираю команду из плагина мне выдает вот это

### ISSUE THREAD

**Issue by marakaybo** [By1337/BAirDrop#1]
![image](https://github.com/By1337/BAirDrop/assets/143234019/be0c6375-8cab-4452-bde7-72550a26a3c9)

был бы рад помощи, плагин нам очень понравился

**Comment by By1337** [comment]
Ошибки в консоли?

**Comment by marakaybo** [comment]
> 

[18:04:26 ERROR]: null
вот такая ошибка

**Comment by By1337** [comment]
Полностью ошибку пришли

**Comment by marakaybo** [comment]
Проблему решил, через команду /plugins я узнал, что вместе с bairdrops не работает и wordguard, после переустановки все работает
