### ISSUE TITLE
предложение по nbt

### ISSUE THREAD

**Issue by 44wrw44** [By1337/BAirDrop#7]
Добавь возможность использовать nbt теги вещей и блоков, я прост хочу сделать, что бы в зависимости от времени открытия маяк возрождения заполнял светокамень 
> тип: respawn_anchor[charges=1]

**Comment by By1337** [comment]
Можно использовать команду setblock.
Если аирдроп в другом мире то так `execute in minecraft:the_end run setblock {x} {y} {z} minecraft:respawn_anchor[charges=4]`
